### ISSUE TITLE
Fetching a publication, modifying, and republishing fails

### ISSUE THREAD

**Issue by svenvanderburg** [fair-workflows/nanopub#110]
## How to reproduce
```python
>>> publication = client.fetch('http://purl.org/np/RApJG4fwj0szOMBMiYGmYvd5MCtRle6VbwkMJUb1SxxDM')
>>> publication.assertion.add((rdflib.URIRef('http://example.org/timbernerslee'),
>>>                                               rdflib.RDF.type,
>>>                                               rdflib.FOAF.Person))     
>>> client.publish(publication)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-64-86cb32f8e4cf> in <module>
----> 1 client.publish(publication)

~/projects/fair-workflows/nanopub/nanopub/client.py in publish(self, publication)
    318 
    319         # Sign the nanopub and publish it
--> 320         signed_file = self.java_wrapper.sign(unsigned_fname)
    321         nanopub_uri = self.java_wrapper.publish(signed_file)
    322         publication_info = {'nanopub_uri': nanopub_uri}

~/projects/fair-workflows/nanopub/nanopub/java_wrapper.py in sign(self, unsigned_file)
     43     def sign(self, unsigned_file: Union[str, Path]) -> str:
     44         unsigned_file = str(unsigned_file)
---> 45         self._run_command(f'{NANOPUB_JAVA_SCRIPT} sign ' + unsigned_file)
     46         return self._get_signed_file(unsigned_file)
     47 

~/projects/fair-workflows/nanopub/nanopub/java_wrapper.py in _run_command(command)
     39                                + PROFILE_INSTRUCTIONS_MESSAGE)
     40         elif result.returncode != 0:
---> 41             raise RuntimeError(f'Error in nanopub java application: {stderr}')
     42 
     43     def sign(self, unsigned_file: Union[str, Path]) -> str:

RuntimeError: Error in nanopub java application: java.security.SignatureException: Seems to have trusty URI before signing: http://purl.org/np/RApJG4fwj0szOMBMiYGmYvd5MCtRle6VbwkMJUb1SxxDM
	at org.nanopub.extra.security.SignNanopub.signAndTransform(SignNanopub.java:150)
	at org.nanopub.extra.security.SignNanopub.signAndTransform(SignNanopub.java:144)
	at org.nanopub.extra.security.SignNanopub.writeAsSignedTrustyNanopub(SignNanopub.java:203)
	at org.nanopub.extra.security.SignNanopub$1.handleNanopub(SignNanopub.java:118)
	at org.nanopub.MultiNanopubRdfHandler.finishAndReset(MultiNanopubRdfHandler.java:128)
	at org.nanopub.MultiNanopubRdfHandler.endRDF(MultiNanopubRdfHandler.java:123)
	at org.eclipse.rdf4j.rio.turtle.TurtleParser.parse(TurtleParser.java:201)
	at org.nanopub.MultiNanopubRdfHandler.process(MultiNanopubRdfHandler.java:61)
	at org.nanopub.MultiNanopubRdfHandler.process(MultiNanopubRdfHandler.java:47)
	at org.nanopub.extra.security.SignNanopub.run(SignNanopub.java:113)
	at org.nanopub.extra.security.SignNanopub.main(SignNanopub.java:75)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.nanopub.Run.run(Run.java:76)
	at org.nanopub.Run.main(Run.java:27)
java.lang.RuntimeException: java.security.SignatureException: Seems to have trusty URI before signing: http://purl.org/np/RApJG4fwj0szOMBMiYGmYvd5MCtRle6VbwkMJUb1SxxDM
```
This should
* [ ] When modifying a `Publication` object all references to the original nanopub should be replaced with DUMMY_NANOPUB_URI, and a wasDerivedFrom triple should be added to the provenance pointing to the old nanopub.
* [ ] Publishing this modified publication should work

Some ideas:
* Also the identifiers of the subgraphs (which are sub:Assertion, sub:Provenance etc.) need to be changed
* Maybe one could use `rdflib.term.bind()` with `replace=True`.

**Comment by svenvanderburg** [comment]
See the workaround I did [in this notebook](https://github.com/fair-workflows/nanopub/blob/94c0291a3839638274f949dcf9b67c26c5770534/examples/blog_post_code.ipynb) for inspiration.

**Comment by svenvanderburg** [comment]
So to fix this the references to the original publication should be changed. The question is where in the code we should do this. Options:
1. In NanopubClient.fetch(), so a fetched Publication is completely stripped from all it's original references, it only has a reference to the nanopub in its `source_uri` property. The problem with this is that often we just want to look at fetched publications and not republish them. So then suddenly all the references are different than the original nanopublication rdf.
2. We can implement keeping track of whether a publication is modified. This involves extending the Publication object with setters and getters. Then only when a publication is modified we replace the original reference with DUMMY_NANOPUB_URI.
3. We provide a helper function `prepare_nanopub_for_modification` that replaces the references. It is used by the user in this specific case, we document it well.

@raar1 what do you think?

**Comment by raar1** [comment]
The most important thing is that there are sufficient checks to prevent people publishing a nanopub that has not changed at all. I agree with the solution you propose as probably good enough. I was thinking of making Nanopub objects immutable, so any 'modification' actually results in a new object. I'm not sure if that would simplify this issue?

**Comment by svenvanderburg** [comment]
Plan:
* Upon publishing we check whether the nanopub comes from somewhere. In this case we raise an error. Unless you pass a keyword argument `publish_derived`. In that case we replace all selfreferences with the dummy uri, and add a derived_from.

**Comment by svenvanderburg** [comment]
See #142, it introduces the userfriendly error message pointing to this issue.
