### ISSUE TITLE
Fix FileAlreadyExistsException when reusing old RSA keys

### ISSUE THREAD

**Issue by svenvanderburg** [fair-workflows/nanopub#126]

**Comment by rcelebi** [comment]
Error message:
 
It seems you already have RSA keys for nanopub. Would you like to replace them? [y/N]: n
Traceback (most recent call last):
  File "/Users/remzicelebi/opt/anaconda3/bin/setup_nanopub_profile", line 8, in <module>
    sys.exit(main())
  File "/Users/remzicelebi/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/remzicelebi/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/remzicelebi/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/remzicelebi/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/remzicelebi/opt/anaconda3/lib/python3.8/site-packages/nanopub/setup_nanopub_profile.py", line 90, in main
    JavaWrapper().make_keys(path_name=DEFAULT_KEYS_PATH_PREFIX)
  File "/Users/remzicelebi/opt/anaconda3/lib/python3.8/site-packages/nanopub/java_wrapper.py", line 87, in make_keys
    self._run_command(f'{NANOPUB_JAVA_SCRIPT} mkkeys -a RSA -f {path_name}')
  File "/Users/remzicelebi/opt/anaconda3/lib/python3.8/site-packages/nanopub/java_wrapper.py", line 42, in _run_command
    raise RuntimeError(f'Error in nanopub-java when running {command}: {stderr}')
RuntimeError: Error in nanopub-java when running nanopub-java mkkeys -a RSA -f /Users/remzicelebi/.nanopub/id: java.nio.file.FileAlreadyExistsException: Key file already exists: /Users/remzicelebi/.nanopub/id_rsa.pub
	at org.nanopub.extra.security.MakeKeys.make(MakeKeys.java:58)
	at org.nanopub.extra.security.MakeKeys.run(MakeKeys.java:49)
	at org.nanopub.extra.security.MakeKeys.main(MakeKeys.java:38)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.nanopub.Run.run(Run.java:76)
	at org.nanopub.Run.main(Run.java:27)

**Comment by svenvanderburg** [comment]
This should actually not trigger making new keys...
